#!/usr/bin/env python3
"""
UART Data Sender for ESP32 Telematics Testing
Generated by SmartWheels GenX

Sends CAN-format data to the ESP32 via serial port.
Protocol: SIGNAL_NAME,VALUE\\n

Usage:
    python test_uart_sender.py
    python test_uart_sender.py --port COM6 --baud 115200 --interactive
"""

import serial
import time
import sys
import argparse


def send_can_data(port, baudrate, data_list):
    try:
        print(f"Opening serial port: {port} at {baudrate} baud...")
        ser = serial.Serial(
            port=port,
            baudrate=baudrate,
            bytesize=serial.EIGHTBITS,
            parity=serial.PARITY_NONE,
            stopbits=serial.STOPBITS_ONE,
            timeout=1,
            xonxoff=False,
            rtscts=False,
            dsrdtr=False
        )
        time.sleep(0.5)
        print("Serial port opened successfully!")
        print("-" * 60)

        for signal_name, value in data_list:
            message = f"{signal_name},{value}\n"
            print(f"Sending: {repr(message)}")
            print(f"  Bytes: {' '.join(f'{b:02X}' for b in message.encode('utf-8'))}")
            ser.write(message.encode('utf-8'))
            ser.flush()
            time.sleep(0.1)

        print("-" * 60)
        print(f"Successfully sent {len(data_list)} messages!")
        ser.close()

    except serial.SerialException as e:
        print(f"Error opening serial port: {e}")
        print(f"\nTroubleshooting:")
        print(f"  1. Check if port '{port}' exists")
        print(f"  2. Ensure no other program is using the port")
        print(f"  3. Check device manager (Windows) or dmesg (Linux)")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        ser.close()
        sys.exit(0)


def interactive_mode(port, baudrate):
    try:
        print(f"Opening serial port: {port} at {baudrate} baud...")
        ser = serial.Serial(port=port, baudrate=baudrate,
                            bytesize=serial.EIGHTBITS, parity=serial.PARITY_NONE,
                            stopbits=serial.STOPBITS_ONE, timeout=1)
        time.sleep(0.5)
        print("Serial port opened successfully!")
        print("-" * 60)
        print("Interactive Mode — Type: SIGNAL_NAME,VALUE")
        print("Examples: Speed,100   ENGINE_RPM,2500   THROTTLE,0x5A")
        print("Type 'quit' or 'exit' to stop")
        print("-" * 60)

        while True:
            try:
                user_input = input("Enter message: ").strip()
                if user_input.lower() in ['quit', 'exit', 'q']:
                    break
                if not user_input:
                    continue
                if not user_input.endswith('\n'):
                    user_input += '\n'
                print(f"Sending: {user_input.strip()}")
                ser.write(user_input.encode('utf-8'))
                ser.flush()
            except KeyboardInterrupt:
                break

        ser.close()
        print("\nSerial port closed.")

    except serial.SerialException as e:
        print(f"Error: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description='Send CAN data to ESP32 Telematics via UART',
        epilog="""
Examples:
  python test_uart_sender.py
  python test_uart_sender.py --port COM7
  python test_uart_sender.py --interactive
  python test_uart_sender.py --baud 9600
        """
    )
    parser.add_argument('--port', '-p', type=str, default='COM9',
                        help='Serial port (default: COM6)')
    parser.add_argument('--baud', '-b', type=int, default=115200,
                        help='Baud rate (default: 115200)')
    parser.add_argument('--interactive', '-i', action='store_true',
                        help='Interactive mode — manually enter messages')
    args = parser.parse_args()

    print("=" * 60)
    print("ESP32 Telematics UART Data Sender — SmartWheels GenX")
    print("=" * 60)
    print(f"Port: {args.port}  |  Baud: {args.baud}")
    print("=" * 60)

    if args.interactive:
        interactive_mode(args.port, args.baud)
    else:
        # Default test signals — edit as needed
        test_data = [
            ("Speed",       100),
            ("ENGINE_RPM",  2500),
            # ("THROTTLE_POS", "0x5A"),
            # ("COOLANT_TEMP", 85),
            # ("BATTERY_VOLTAGE", 200),
            # ("FUEL_LEVEL", "0x64"),
        ]
        print("\nSending test data...")
        while(True):
            send_can_data(args.port, args.baud, test_data)
            time.sleep(2)


if __name__ == "__main__":
    main()
