/**
 * uart_config.h — Generated by SmartWheels GenX
 * Date:   22-04-2026
 * Author: praga
 *
 * Logger channel (UART0/USB): system debug output
 * Data channel   (UART1):     CAN data from MCU
 */

#ifndef UART_CONFIG_H
#define UART_CONFIG_H

// ===== LOGGER CHANNEL (UART0 / USB CDC) =====
#define UART_LOGGER_NUM      0
#define UART_LOGGER_BAUD     115200
#define UART_LOGGER_TX_PIN   21
#define UART_LOGGER_RX_PIN   20

// ===== DATA CHANNEL (UART1) =====
#define UART_DATA_NUM        1
#define UART_DATA_BAUD       115200
#define UART_DATA_TX_PIN     4
#define UART_DATA_RX_PIN     5

// ===== BUFFER SIZES =====
#define UART_LOGGER_RX_BUFFER_SIZE  256
#define UART_LOGGER_TX_BUFFER_SIZE  256
#define UART_DATA_RX_BUFFER_SIZE    1024
#define UART_DATA_TX_BUFFER_SIZE    256
#define UART_DATA_LINE_BUFFER_SIZE  128

// ===== TIMEOUT =====
#define UART_READ_TIMEOUT_MS  100

// ===== LOGGER CONTROL =====
#define UART_LOGGER_ENABLED         1
#define UART_LOGGER_RUNTIME_CONTROL 1

#endif // UART_CONFIG_H
