/**
 * @file uart_manager.h
 * @brief UART Manager for ESP32 telematics system
 *
 * Manages two UART channels:
 * - Logger Channel: System logging and debugging output (UART0/USB)
 * - Data Channel:   Receiving CAN data from MCU (UART1)
 *
 * Generated by SmartWheels GenX
 */

#ifndef UART_MANAGER_H
#define UART_MANAGER_H

#include <Arduino.h>
#include <HardwareSerial.h>
#include "../config/uart_config.h"

typedef enum {
    UART_CHANNEL_LOGGER = 0,
    UART_CHANNEL_DATA   = 1
} UARTChannel;

class UARTManager {
public:
    void init();
    void update();

    // Logger channel (UART0)
    void   loggerWrite(const char* message);
    void   loggerPrintf(const char* format, ...);
    void   loggerWriteLine(const char* message);
    int    loggerAvailable();
    int    loggerRead();
    size_t loggerReadBytes(char* buffer, size_t length);
    void   setLoggerEnabled(bool enable);
    bool   isLoggerEnabled();

    // Data channel (UART1)
    int    dataAvailable();
    int    dataRead();
    int    dataWrite(const char* buffer, size_t length);
    size_t dataReadBytes(uint8_t* buffer, size_t length);

    bool   isChannelInitialized(UARTChannel channel);

private:
    HardwareSerial* loggerSerial;
    HardwareSerial* dataSerial;

    bool loggerInitialized;
    bool dataInitialized;

    #if UART_LOGGER_RUNTIME_CONTROL
    bool loggerEnabled;
    #endif

    char     dataLineBuffer[UART_DATA_LINE_BUFFER_SIZE];
    uint16_t dataLineBufferIndex;

    void initLoggerChannel();
    void initDataChannel();
    void processDataChannel();
    void parseCANDataLine(const char* line);
};

extern UARTManager uartManager;

// Compile-time logging macros
#if UART_LOGGER_ENABLED
    #define UART_LOG(msg)    uartManager.loggerWrite(msg)
    #define UART_LOG_LN(msg) uartManager.loggerWriteLine(msg)
    #define UART_LOG_F(...)  uartManager.loggerPrintf(__VA_ARGS__)
#else
    #define UART_LOG(msg)    ((void)0)
    #define UART_LOG_LN(msg) ((void)0)
    #define UART_LOG_F(...)  ((void)0)
#endif

#endif // UART_MANAGER_H
