/**
 * @file mqtt_manager.h
 * @brief MQTT Manager for ESP32 telematics system
 *
 * Manages MQTT connection with state machine, message buffering,
 * CAN signal publishing, and periodic device health reporting.
 *
 * Generated by SmartWheels GenX
 */

#ifndef MQTT_MANAGER_H
#define MQTT_MANAGER_H

#include <Arduino.h>
#include <PubSubClient.h>
#include <WiFi.h>
#include "../config/mqtt_config.h"

// #define PUBLISH_HEALTH

enum MQTTState {
    MQTT_STATE_DISCONNECTED,
    MQTT_STATE_CONNECTING,
    MQTT_STATE_CONNECTED,
    MQTT_STATE_RECONNECTING,
    MQTT_STATE_ERROR
};

struct MQTTMessage {
    char    topic[64];
    char    payload[MQTT_JSON_BUFFER_SIZE];
    uint8_t qos;
    bool    retain;
    bool    valid;
};

class MQTTManager {
public:
    MQTTManager();

    void init();
    void update();

    // Connection
    bool      connect();
    void      disconnect();
    bool      isConnected();
    MQTTState getState();

    // Publishing
    bool publishCANSignal(const char* signalName, long value);
    bool publishDeviceHealth();

    // Buffer
    int  getBufferCount();
    bool isBufferFull();
    void clearBuffer();

private:
    WiFiClient    wifiClient;
    PubSubClient  mqttClient;

    MQTTState     currentState;
    unsigned long lastConnectionAttempt;
    int           reconnectionAttempts;
    unsigned long lastHealthPublish;

    MQTTMessage messageBuffer[MQTT_BUFFER_SIZE];
    int         bufferWriteIndex;
    int         bufferReadIndex;
    int         bufferedMessageCount;

    void handleConnectionState();
    void attemptReconnection();
    void processBufferedMessages();
    bool bufferMessage(const char* topic, const char* payload, uint8_t qos, bool retain);
    bool publishMessage(const char* topic, const char* payload, uint8_t qos, bool retain);
    void buildCANSignalJSON(char* buffer, size_t bufferSize, const char* signalName, long value);
    void buildDeviceHealthJSON(char* buffer, size_t bufferSize);
    void buildFullTopic(char* buffer, size_t bufferSize, const char* relativeTopic);
    unsigned long getTimestamp();
};

extern MQTTManager mqttManager;

#endif // MQTT_MANAGER_H
