/**
 * wifi_config.h — Generated by SmartWheels GenX
 * Date:   22-04-2026
 * Author: praga
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

// ===== WiFi CREDENTIALS =====
#define WIFI_SSID     "iPhone"
#define WIFI_PASSWORD "Sasi12345"

// ===== CONNECTION PARAMETERS =====
#define WIFI_CONNECTION_TIMEOUT_MS   10000
#define WIFI_RECONNECT_INTERVAL_MS   5000
#define WIFI_MAX_RECONNECT_ATTEMPTS  10

#endif // WIFI_CONFIG_H
